"""add bonus balance

Revision ID: cdc5d4bf5962
Revises: 47bed0b7bcdb
Create Date: 2026-08-17 09:43:38.431812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc5d4bf5962'
down_revision: Union[str, None] = '47bed0b7bcdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bonus_balance', sa.Integer(), server_default='1000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bonus_balance')
    # ### end Alembic commands ###
